---
- name: Install Ansible Desktop
  hosts: localhost
  connection: local
  become: true
  vars:
    - user: diego
    - home: "/home/{{ user }}"
    - localbin: "{{ home }}/.local/bin"
    - github_username: diegoaldarondo
    - ssh_key: "{{ home }}/.ssh/id_25519"
    - ssh_key_pub: "{{ home }}/.ssh/id_25519.pub"
    - lazygit_dest: "{{ localbin }}/lazygit"
    - miniconda_script: "{{ home }}/miniconda.sh"
    - miniconda_install_dir: "{{ home }}/miniconda3"
    - playbook_dir: "{{ home }}/ansible_desktop"
    - go_version: "1.19.6"
    - go_install_dir: "/usr/local/go"
    - apptainer_repo_url: "https://github.com/apptainer/apptainer.git"
    - apptainer_repo_dir: "{{ home }}/apptainer"
    - virtualbox_deb_url: "https://download.virtualbox.org/virtualbox/7.0.12/virtualbox-7.0_7.0.12-159484~Debian~bookworm_amd64.deb"
    - virtualbox_deb_path: "/tmp/virtualbox.deb"
    - vault_file: vault/secrets.yml

  tasks:
    - name: Make .local/bin
      file:
        path: "{{ localbin }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
  
    - include_tasks: tasks/secrets.yml
    - include_tasks: tasks/package.yml
    - include_tasks: tasks/flatpaks.yml
    - include_tasks: tasks/firefox_extensions.yml
    - include_tasks: tasks/fzf.yml
    - include_tasks: tasks/lazygit.yml
    - include_tasks: tasks/ripgrep.yml
    - include_tasks: tasks/notes.yml
    - include_tasks: tasks/miniconda.yml
    - include_tasks: tasks/vscode.yml
    - include_tasks: tasks/radio.yml
    - include_tasks: tasks/shell_gpt.yml
    - include_tasks: tasks/gnome.yml
    - include_tasks: tasks/apptainer.yml
    - include_tasks: tasks/anydesk.yml
    - include_tasks: tasks/virtualbox.yml
    - include_tasks: tasks/scripts.yml
    - include_tasks: tasks/uninstall.yml
    - include_tasks: tasks/dotfiles.yml


      

      
      
