- name: Create symlink for .bashrc file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/bash/.bashrc"
    dest: "{{ home }}/.bashrc"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
    force: yes

- name: Create symlink for .bash_aliases file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/bash/.bash_aliases"
    dest: "{{ home }}/.bash_aliases"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
    force: yes

- name: Create symlink for .gitconfig file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/git/.gitconfig"
    dest: "{{ home }}/.gitconfig"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
    force: yes

- name: Create symlink for .ssh config file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/ssh/config"
    dest: "{{ home }}/.ssh/config"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
    force: yes

- name: Create symlink for radio config file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/radio/.radio-active-alias"
    dest: "{{ home }}/.radio-active-alias"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
    force: yes

- name: Create symlink for vscode settings file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/vscode/settings.json"
    dest: "/home/diego/.config/Code/User/settings.json"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
    force: yes

- name: Create symlink for vscode keybindings file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/vscode/keybindings.json"
    dest: "/home/diego/.config/Code/User/keybindings.json"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
    force: yes