- name: Create symlink for .bashrc file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/bash/.bashrc"
    dest: "{{ home }}/.bashrc"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
    force: yes

- name: Create symlink for .bash_aliases file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/bash/.bash_aliases"
    dest: "{{ home }}/.bash_aliases"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
    force: yes

- name: Create symlink for .tmux.conf file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/tmux/.tmux.conf"
    dest: "{{ home }}/.tmux.conf"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
    force: yes

- name: Create symlink for .gitconfig file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/git/.gitconfig"
    dest: "{{ home }}/.gitconfig"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
    force: yes

- name: Create symlink for .ssh config file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/ssh/config"
    dest: "{{ home }}/.ssh/config"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
    force: yes

- name: Create symlink for radio config file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/radio/.radio-active-alias"
    dest: "{{ home }}/.radio-active-alias"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
    force: yes

- name: Create symlink for vscode settings file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/vscode/settings.json"
    dest: "/home/diego/.config/Code/User/settings.json"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
    force: yes

- name: Create symlink for vscode keybindings file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/vscode/keybindings.json"
    dest: "/home/diego/.config/Code/User/keybindings.json"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
    force: yes

- name: Create symlink for vscode tasks file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/vscode/tasks.json"
    dest: "/home/diego/.config/Code/User/tasks.json"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
    force: yes

- name: Create symlink for shell_gpt files
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/shell_gpt/"
    dest: "{{ home }}/.config/shell_gpt"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
    force: yes

- name: Create symlink for lazygit .config
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/lazygit"
    dest: "{{ home }}/.config/lazygit"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
    force: yes

- name: Create symlink for .xinitrc file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/xorg/.xinitrc"
    dest: "{{ home }}/.xinitrc"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
    force: yes
