- name: Ensure directories exist
  file:
    path: "/usr/lib/firefox/distribution"
    state: directory
    mode: '0755'
- name: Configure Firefox
  copy:
    dest: "/usr/lib/firefox/distribution/policies.json"
    content: |
      {
        "policies": {
          "Extensions": {
            "Install": [
              "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi",
              "https://addons.mozilla.org/firefox/downloads/latest/vimium/latest.xpi"
            ],
            "Uninstall": [
              "{bad-addon-id}"
            ],
            "Locked":  [
              "uBlock0@raymondhill.net",
              "vimium@philc.com"
            ]
          }
        }
      }
    mode: '0644'
