- name: Ensure ~/.secrets exists
  become_user: "{{ user }}"
  file:
    path: "{{ home }}/.secrets"
    state: touch
    mode: '0700'

- name: Write secrets to ~/.secrets
  become_user: "{{ user }}"
  copy:
    content: "{{ lookup('template', '{{ playbook_dir}}/vault/secrets.yml') }}"
    dest: "{{ home }}/.secrets"
    mode: '0700'