customCommands:
  - key: '<f8>'
    command: "git diff --cached | sgpt --role=commit | git commit --file=-"
    context:  "global"
    description: "Commit staged changes using sgpt"
  - key: '<f9>'
    command: "git diff --cached | sgpt --role=commit_critic | code -"
    context:  "global"
    description: "Critique staged changes using sgpt"
